name: auto merge
on:
  workflow_call:
    inputs:
      pullRequestId:
        description: node ID of the PR to update
        required: true
        type: string
      mergeMethod:
        description: one of https://docs.github.com/en/graphql/reference/enums#pullrequestmergemethod
        default: SQUASH
        type: string
    secrets:
      token:
        required: true
jobs:
  enable:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@975fed23f983de9aa6f637f9875f94c6fb0a4255 # tag=v2.2.22
        id: enablePullRequestAutoMerge
        with:
          query: |
            mutation(
              $pullrequestid: ID!,
              $mergemethod: PullRequestMergeMethod!
            ) {
                enablePullRequestAutoMerge(input: {
                  pullRequestId: $pullrequestid,
                  mergeMethod: $mergemethod
                }) {
                clientMutationId
                pullRequest {
                  id
                  state
                  autoMergeRequest {
                    enabledAt
                    enabledBy {
                      login
                    }
                  }
                }
              }
            }

          pullrequestid: ${{ inputs.pullRequestId }}
          mergemethod: ${{ inputs.mergeMethod }}
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
      - run: "echo '${{ steps.enablePullRequestAutoMerge.outputs.data }}'"