name: manually deployed
on:
  workflow_call:
    inputs:
      sha:
        description: sha
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@d4560e157075e2d93aa3022b5b51a42a880f1f93 # tag=v6.3.0
        env:
          SHA: ${{ inputs.sha }}
        with:
          github-token: ${{ secrets.token }}
          script: |
            await github.rest.repos.createCommitStatus({
              ...context.repo,
              sha:         process.env.SHA,
              state:       'success',
              context:     'deploy',
              description: 'Deploy attested by ${{ github.actor }}',
              target_url:  'https://github.com/${{ github.repository }}/commit/${{ inputs.sha }}/checks'
            });