name: Renovate
on:
  push:
    branches:
      - $default-branch
  workflow_dispatch:
  workflow_call:
    secrets:
      RENOVATE_APP_PEM:
        required: true
      RENOVATE_APP_ID:
        required: true
  schedule:
    - cron:  '0 */4 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@0.21
        with:
          APP_PEM: ${{ secrets.RENOVATE_APP_PEM }}
          APP_ID: ${{ secrets.RENOVATE_APP_ID }}
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - name: Renovate
        uses: renovatebot/github-action@6030949931ad2285e5e0fbe5101c2052c540262c # tag=v26.21.7
        with:
          configurationFile: renovate.js
          token: 'x-access-token:${{ steps.get_token.outputs.app_token }}'
