name: Renovate
on:
  push:
    branches:
      - $default-branch
  workflow_dispatch:
  workflow_call:
    secrets:
      RENOVATE_APP_PEM:
        required: true
      RENOVATE_APP_ID:
        required: true
  schedule:
    - cron:  '0 */4 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Get token
        id: get_token
        uses: machine-learning-apps/actions-app-token@0.21
        with:
          APP_PEM: ${{ secrets.RENOVATE_APP_PEM }}
          APP_ID: ${{ secrets.RENOVATE_APP_ID }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Renovate
        uses: renovatebot/github-action@v32.32.2
        with:
          configurationFile: renovate.js
          token: 'x-access-token:${{ steps.get_token.outputs.app_token }}'
