name: open issues on workflow failure, close on success
on:
  workflow_call:
  workflow_run:
    workflows:
      - renovate
    types:
      - completed
jobs:
  workflow-failure-issues:
    uses: urcomputeringpal/.github/.github/workflows/workflow-failure-issues.yaml@main
    if: |
      (
        github.event_name == 'schedule' ||
        endsWith(github.ref, github.event.repository.default_branch)
      )
